brand_dict_reps = {
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
}

brand_dict_ft = {
             "Allianz" : ["72","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["73","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["74","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["75","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["76","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["77","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["78","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["79","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["80","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["81","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["82","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["83","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["84","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["85","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["86","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["87","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["88","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["89","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["90","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["91","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["92","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["93","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["94","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["95","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["96","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["97","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["98","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["99","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["100","18,694","+23%","RANK UNCHANGED"],
             }
