brand_dict_reps = {
             "Colgate" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Danone" : ["Allianz","allianzuknews","AllianzPartners"],
             "Cartier" : ["Allianz","allianzuknews","AllianzPartners"],
             "Ferrari" : ["Allianz","allianzuknews","AllianzPartners"],
             "Santander" : ["Allianz","allianzuknews","AllianzPartners"],
             "Dior" : ["Allianz","allianzuknews","AllianzPartners"],
             "Kellogg’s" : ["Allianz","allianzuknews","AllianzPartners"],
             "FedEx" : ["Allianz","allianzuknews","AllianzPartners"],
             "Corona" : ["Allianz","allianzuknews","AllianzPartners"],
             "LinkedIn" : ["Allianz","allianzuknews","AllianzPartners"],
             "DHL" : ["Allianz","allianzuknews","AllianzPartners"],
             "Caterpillar" : ["Allianz","allianzuknews","AllianzPartners"],
             "Xiaomi" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Jack Daniel’s" : ["Allianz","allianzuknews","AllianzPartners"],
             "Huawei" : ["Allianz","allianzuknews","AllianzPartners"],
             "Kia" : ["Allianz","allianzuknews","AllianzPartners"],
             "Tiffany & Co." : ["Allianz","allianzuknews","AllianzPartners"],
             "Prada" : ["Allianz","allianzuknews","AllianzPartners"],
             "Hewlett Packard Enterprise" : ["Allianz","allianzuknews","AllianzPartners"],
             "Panasonic" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
}

brand_dict_ft = {
             "Colgate" : ["72","10,130","+5%","DOWN 4 PLACES"],
             "Danone" : ["73","9,528","-3%","DOWN 8 PLACES"],
             "Cartier" : ["74","9,521","+17%","DOWN 1 PLACE"],
             "Ferrari" : ["75","9,365","+31%","UP 1 PLACE"],
             "Santander" : ["76","9,015","+11%","DOWN 2 PLACES"],
             "Dior" : ["77","8,919","+27%","RANK UNCHANGED"],
             "Kellogg’s" : ["78","8,747","+1%","DOWN 6 PLACES"],
             "FedEx" : ["79","8,166","+8%","DOWN 4 PLACES"],
             "Corona" : ["80","7,764","+12%","DOWN 2 PLACES"],
             "LinkedIn" : ["81","7,595","+19%","UP 2 PLACES"],
             "DHL" : ["82","7,518","+11%","DOWN 2 PLACES"],
             "Caterpillar" : ["83","7,397","+14%","DOWN 1 PLACE"],
             "Xiaomi" : ["84","7,326","NEW","NEW"],
             "Jack Daniel’s" : ["85","7,171","+10%","DOWN 4 PLACES"],
             "Huawei" : ["86","6,634","+7%","DOWN 1 PLACE"],
             "Kia" : ["87","6,612","+9%","DOWN 1 PLACE"],
             "Tiffany & Co." : ["88","6,552","+19%","UP 4 PLACES"],
             "Prada" : ["89","6,548","+21%","UP 5 PLACES"],
             "Hewlett Packard Enterprise" : ["90","6,486","+3%","DOWN 6 PLACES"],
             "Panasonic" : ["91","6,337","+9%","DOWN 3 PLACES"],
             "Allianz" : ["92","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["93","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["94","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["95","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["96","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["97","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["98","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["99","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["100","18,694","+23%","RANK UNCHANGED"],
             }
