brand_dict_reps = {
             "Hermès" : ["Hermes_Paris"],
             "J.P. Morgan" : ["jpmorgan","JPMWealth","JPMorganAM"],
             "YouTube" : ["TeamYouTube","YouTube","YouTubeCreators","youtubemusic","YouTubeGaming","YouTubeIndia"],
             "Honda" : ["Honda","HondaCanada","Honda_UK","HondaCustSvc"],
             "American Express" : ["AmericanExpress","AskAmex","AmexBusiness"],
             "IKEA" : ["IKEA","IKEAUK","IKEAUSA","IKEACanada"],
             "UPS" : ["TheUPSStore","UPS","UPSers"],
             "Gucci" : ["gucci"],
             "Accenture" : ["Accenture","AccentureStrat"],
             "Pepsi" : ["PepsiCanada","PepsiMaxUK","pepsi","PepsiGlobal"],
             "GE" : ["generalelectric","GE_Canada","GE_Appliances","GEpublicaffairs"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Hyundai" : ["Hyundai_Global","Hyundai","HyundaiCanada","Hyundai_UK"],
             "Salesforce" : ["salesforce","SalesforceOrg","SalesforceNews","SalesforceAdmns","SalesforceDevs"],
             "Visa Inc." : ["Allianz","allianzuknews","AllianzPartners"],
             "PayPal" : ["Allianz","allianzuknews","AllianzPartners"],
             "Sony" : ["Allianz","allianzuknews","AllianzPartners"],
             "Netflix" : ["Allianz","allianzuknews","AllianzPartners"],
             "Mastercard" : ["Allianz","allianzuknews","AllianzPartners"],
             "adidas" : ["Allianz","allianzuknews","AllianzPartners"],
             "AXA Group" : ["Allianz","allianzuknews","AllianzPartners"],
             "Budweiser" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Nescafé" : ["Allianz","allianzuknews","AllianzPartners"],
             "Audi" : ["Allianz","allianzuknews","AllianzPartners"],
             "Zara" : ["Allianz","allianzuknews","AllianzPartners"],
             "Volkswagen" : ["Allianz","allianzuknews","AllianzPartners"],
             "Goldman Sachs Group" : ["Allianz","allianzuknews","AllianzPartners"],
             "Ford Motor Company" : ["Allianz","allianzuknews","AllianzPartners"],
             "Starbucks" : ["Allianz","allianzuknews","AllianzPartners"],
             "Pampers" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Porsche" : ["Allianz","allianzuknews","AllianzPartners"],
             "Airbnb" : ["Allianz","allianzuknews","AllianzPartners"],
             "Siemens" : ["Allianz","allianzuknews","AllianzPartners"],
             "H&M" : ["Allianz","allianzuknews","AllianzPartners"],
             "Citi" : ["Allianz","allianzuknews","AllianzPartners"],
             "L’Oréal" : ["Allianz","allianzuknews","AllianzPartners"],
             "Philips" : ["Allianz","allianzuknews","AllianzPartners"],
             "eBay" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Nissan" : ["Allianz","allianzuknews","AllianzPartners"],
             "HP Inc." : ["Allianz","allianzuknews","AllianzPartners"],
             "LEGO" : ["Allianz","allianzuknews","AllianzPartners"],
             "Red Bull" : ["Allianz","allianzuknews","AllianzPartners"],
             "HSBC" : ["Allianz","allianzuknews","AllianzPartners"],
             "Morgan Stanley" : ["Allianz","allianzuknews","AllianzPartners"],
             "Nestlé" : ["Allianz","allianzuknews","AllianzPartners"],
             "Nintendo" : ["Allianz","allianzuknews","AllianzPartners"],
             "3M" : ["Allianz","allianzuknews","AllianzPartners"],
             "Spotify" : ["Allianz","allianzuknews","AllianzPartners"],
             "Gillette" : ["Allianz","allianzuknews","AllianzPartners"],
}

brand_dict_ft = {
             "Hermès" : ["23","27,398","+27%","RANK UNCHANGED"],
             "J.P. Morgan" : ["24","24,335","+14%","RANK UNCHANGED"],
             "YouTube" : ["25","24,268","+16%","UP 1 PLACE"],
             "Honda" : ["26","22,837","+7%","DOWN 1 PLACE"],
             "American Express" : ["27","22,117","+16%","UP 3 PLACES"],
             "IKEA" : ["28","21,928","+9%","DOWN 1 PLACE"],
             "UPS" : ["29","21,164","+9%","RANK UNCHANGED"],
             "Gucci" : ["30","20,417","+23%","UP 3 PLACES"],
             "Accenture" : ["31","20,412","+15%","UP 1 PLACE"],
             "Pepsi" : ["32","19,622","+1%","DOWN 4 PLACES"],
             "GE" : ["33","19,093","+4%","DOWN 2 PLACES"],
             "Allianz" : ["34","18,694","+23%","RANK UNCHANGED"],
             "Hyundai" : ["35","17,314","+14%","RANK UNCHANGED"],
             "Salesforce" : ["36","17,311","+17%","UP 2 PLACES"],
             "Visa Inc." : ["37","17,258","+17%","UP 2 PLACES"],
             "PayPal" : ["38","17,058","+19%","UP 4 PLACES"],
             "Sony" : ["39","16,989","+18%","UP 4 PLACES"],
             "Netflix" : ["40","16,375","+9%","DOWN 4 PLACES"],
             "Mastercard " : ["41","16,125","+23%","UP 9 PLACES"],
             "adidas" : ["42","15,931","+19%","UP 7 PLACES"],
             "AXA Group" : ["43","15,747","+17%","UP 5 PLACES"],
             "Budweiser" : ["44","15,487","+3%","DOWN 7 PLACES"],
             "Nescafé" : ["45","15,061","+4%","DOWN 5 PLACES"],
             "Audi" : ["46","14,976","+11%","RANK UNCHANGED"],
             "Zara" : ["47","14,958","+11%","DOWN 2 PLACES"],
             "Volkswagen" : ["48","14,819","+10%","DOWN 1 PLACE"],
             "Goldman Sachs Group" : ["49","14,526","+16%","UP 6 PLACES"],
             "Ford Motor Company" : ["50","14,431","12%","UP 2 PLACES"],
             "Starbucks" : ["51","14,050","+8%","RANK UNCHANGED"],
             "Pampers" : ["52","13,832","-1%","DOWN 8 PLACES"],
             "Porsche" : ["53","13,504","+15%","UP 5 PLACES"],
             "Airbnb" : ["54","13,416","NEW","NEW"],
             "Siemens" : ["55","13,359","+21%","UP 5 PLACES"],
             "H&M" : ["56","12,985","8%","DOWN 13 PLACES"],
             "Citi" : ["57","12,981","+4%","DOWN 3 PLACES"],
             "L’Oréal" : ["58","12,915","+3%","DOWN 5 PLACES"],
             "Philips" : ["59","12,801","+6%","DOWN 2 PLACES"],
             "eBay" : ["60","12,767","+4%","DOWN 4 PLACES"],
             "Nissan" : ["61","12,212","+10%","DOWN 2 PLACES"],
             "HP Inc." : ["62","11,884","+13%","UP 1 PLACE"],
             "LEGO" : ["63","11,846","+30%","UP 8 PLACES"],
             "Red Bull" : ["64","11,547","NEW","NEW"],
             "HSBC" : ["65","11,247","+9%","DOWN 1 PLACE"],
             "Morgan Stanley" : ["66","11,039","+18%","UP 3 PLACES"],
             "Nestlé" : ["67","10,921","+3%","DOWN 5 PLACES"],
             "Nintendo" : ["68","10,676","+16%","UP 2 PLACES"],
             "3M" : ["69","10,505","+8%","DOWN 2 PLACES"],
             "Spotify" : ["70","10,324","+6%","DOWN 4 PLACES"],
             "Gillette" : ["71","10,211","-4%","DOWN 10 PLACES"],
             }
