brand_dict_reps = {
             "Hermès" : ["Hermes_Paris"],
             "J.P. Morgan" : ["jpmorgan","JPMWealth","JPMorganAM"],
             "YouTube" : ["TeamYouTube","YouTube","YouTubeCreators","youtubemusic","YouTubeGaming","YouTubeIndia"],
             "Honda" : ["Honda","HondaCanada","Honda_UK","HondaCustSvc"],
             "American Express" : ["AmericanExpress","AskAmex","AmexBusiness"],
             "IKEA" : ["IKEA","IKEAUK","IKEAUSA","IKEACanada"],
             "UPS" : ["TheUPSStore","UPS","UPSers"],
             "Gucci" : ["gucci"],
             "Accenture" : ["Accenture","AccentureStrat"],
             "Pepsi" : ["PepsiCanada","PepsiMaxUK","pepsi","PepsiGlobal"],
             "GE" : ["generalelectric","GE_Canada","GE_Appliances","GEpublicaffairs"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Hyundai" : ["Hyundai_Global","Hyundai","HyundaiCanada","Hyundai_UK"],
             "Salesforce" : ["salesforce","SalesforceOrg","SalesforceNews","SalesforceAdmns","SalesforceDevs"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],  
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
             "Allianz" : ["Allianz","allianzuknews","AllianzPartners"],
}

brand_dict_ft = {
             "Hermès" : ["23","27,398","+27%","RANK UNCHANGED"],
             "J.P. Morgan" : ["24","24,335","+14%","RANK UNCHANGED"],
             "YouTube" : ["25","24,268","+16%","UP 1 PLACE"],
             "Honda" : ["26","22,837","+7%","DOWN 1 PLACE"],
             "American Express" : ["27","22,117","+16%","UP 3 PLACES"],
             "IKEA" : ["28","21,928","+9%","DOWN 1 PLACE"],
             "UPS" : ["29","21,164","+9%","RANK UNCHANGED"],
             "Gucci" : ["30","20,417","+23%","UP 3 PLACES"],
             "Accenture" : ["31","20,412","+15%","UP 1 PLACE"],
             "Pepsi" : ["32","19,622","+1%","DOWN 4 PLACES"],
             "GE" : ["33","19,093","+4%","DOWN 2 PLACES"],
             "Allianz" : ["34","18,694","+23%","RANK UNCHANGED"],
             "Hyundai" : ["35","17,314","+14%","RANK UNCHANGED"],
             "Salesforce" : ["36","17,311","+17%","UP 2 PLACES"],
             "Allianz" : ["37","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["38","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["39","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["40","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["41","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["42","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["43","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["44","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["45","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["46","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["47","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["48","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["49","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["50","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["51","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["52","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["53","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["54","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["55","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["56","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["57","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["58","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["59","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["60","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["61","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["62","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["63","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["64","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["65","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["66","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["67","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["68","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["69","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["70","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["71","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["72","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["73","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["74","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["75","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["76","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["77","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["78","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["79","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["80","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["81","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["82","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["83","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["84","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["85","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["86","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["87","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["88","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["89","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["90","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["91","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["92","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["93","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["94","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["95","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["96","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["97","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["98","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["99","18,694","+23%","RANK UNCHANGED"],
             "Allianz" : ["100","18,694","+23%","RANK UNCHANGED"],
             }
