brand_dict_reps = {
             "Colgate" : ["CP_News","Colgate"],  
             "Danone" : ["DanoneCanada","Danone"],
             "Cartier" : ["Cartier","Fond_Cartier"],
             "Ferrari" : ["Ferrari","ScuderiaFerrari"],
             "Santander" : ["SantanderUSA","SantanderBankUS","bancosantander"],
             "Dior" : ["Dior"],
             "Kellogg’s" : ["KelloggsCareers","KelloggsUS","KelloggCompany"],
             "FedEx" : ["FedExOffice","FedExHelp","FedEx","FedExCanada"],
             "Corona" : ["coronacanada","CoronaUSA","corona"],
             "LinkedIn" : ["LinkedInMktg","LinkedInHelp","LinkedIn"],
             "DHL" : ["DHLGlobal","DHLCanadaHelp","DHLUS"],
             "Caterpillar" : ["CaterpillarInc"],
             "Xiaomi" : ["XiaomiUSA","Xiaomi"],  
             "Jack Daniel’s" : ["JackDaniels_US"],
             "Huawei" : ["HuaweiUSA","Huawei_devs","Huawei"],
             "Kia" : ["Kia","Kia_Worldwide","KiaCanada"],
             "Tiffany & Co." : ["TiffanyAndCo"],
             "Prada" : ["FondazionePrada","Prada"],
             "Hewlett Packard Enterprise" : ["HPE","HPE_OEM"],
             "Panasonic" : ["Panasonic_mob","PanasonicNA","panasonic"],
             "Johnson & Johnson" : ["JNJNews"],
             "Hennessy" : ["Hennessy","MoetHennessy"],
             "KFC" : ["kfc_canada","TellTheColonel","kfc"],
             "Heineken" : ["HeinekenCA","Heineken_Exp","Heineken_US","Heineken"],
             "Burberry" : ["Allianz","allianzuknews","AllianzPartners"],
             "Canon" : ["Allianz","allianzuknews","AllianzPartners"],
             "Land Rover" : ["Allianz","allianzuknews","AllianzPartners"],
             "MINI" : ["Allianz","allianzuknews","AllianzPartners"],
             "Sephora" : ["Allianz","allianzuknews","AllianzPartners"],
             }

brand_dict_ft = {
             "Colgate" : ["72","10,130","+5%","DOWN 4 PLACES"],
             "Danone" : ["73","9,528","-3%","DOWN 8 PLACES"],
             "Cartier" : ["74","9,521","+17%","DOWN 1 PLACE"],
             "Ferrari" : ["75","9,365","+31%","UP 1 PLACE"],
             "Santander" : ["76","9,015","+11%","DOWN 2 PLACES"],
             "Dior" : ["77","8,919","+27%","RANK UNCHANGED"],
             "Kellogg’s" : ["78","8,747","+1%","DOWN 6 PLACES"],
             "FedEx" : ["79","8,166","+8%","DOWN 4 PLACES"],
             "Corona" : ["80","7,764","+12%","DOWN 2 PLACES"],
             "LinkedIn" : ["81","7,595","+19%","UP 2 PLACES"],
             "DHL" : ["82","7,518","+11%","DOWN 2 PLACES"],
             "Caterpillar" : ["83","7,397","+14%","DOWN 1 PLACE"],
             "Xiaomi" : ["84","7,326","NEW","NEW"],
             "Jack Daniel’s" : ["85","7,171","+10%","DOWN 4 PLACES"],
             "Huawei" : ["86","6,634","+7%","DOWN 1 PLACE"],
             "Kia" : ["87","6,612","+9%","DOWN 1 PLACE"],
             "Tiffany & Co." : ["88","6,552","+19%","UP 4 PLACES"],
             "Prada" : ["89","6,548","+21%","UP 5 PLACES"],
             "Hewlett Packard Enterprise" : ["90","6,486","+3%","DOWN 6 PLACES"],
             "Panasonic" : ["91","6,337","+9%","DOWN 3 PLACES"],
             "Johnson & Johnson" : ["92","6,130","+3%","DOWN 5 PLACES"],
             "Hennessy" : ["93","6,111","+15%","UP 2 PLACES"],
             "KFC" : ["94","6,089","+12%","DOWN 1 PLACE"],
             "Heineken" : ["95","6,003","+5%","DOWN 6 PLACES"],
             "Burberry" : ["96","5,917","+14%","UP 1 PLACE"],
             "Canon" : ["97","5,828","-15%","DOWN 18 PLACES"],
             "Land Rover" : ["98","5,593","+10%","RANK UNCHANGED"],
             "MINI" : ["99","5,579","+7%","DOWN 3 PLACES"],
             "Sephora" : ["100","5,491","+19%","RANK UNCHANGED"],
             }
